### ISSUE TITLE
Signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is marginal trust

### ISSUE THREAD

**Issue by Marcool04** [fwcd/docker-archlinux#5] opened 2023-12-03 10:57 UTC
Hi there,

I have been using your docker images successfully for a while in github actions that I use to build some archlinuxarm packages. But since this morning, the build started failing with this type of error:

```
error: asciidoc: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is marginal trust
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Do you want to delete it? [Y/n] 
:: File /var/cache/pacman/pkg/asciidoc-10.2.0-4-any.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
Errors occurred, no packages were upgraded.
```
(see a full build log here for instance: https://github.com/Marcool04/aarch64_builder/actions/runs/7073772589/job/19254094876 and for comparison's sake, a successful one from the previous day: https://github.com/Marcool04/aarch64_builder/actions/runs/7067021893/job/19239833420)

I wonder if, somehow, when using archlinuxarm, this line here: 
https://github.com/fwcd/docker-archlinux/blob/7d1b454a403f631ff600444f8d2be70e787e241b/Dockerfile#L39 shouldn't have something like `pacman-key --populate archlinuxarm` ? I have tried adapting my build script (notably here: https://github.com/Marcool04/pkgbuilds/blob/main/with-builder-user) to do that later on,  but the runner still fails.

I realize you have made no recent changes that would have caused this, but I'd be grateful for your input as to what might be causing this.

Thanks in advence.
Best regards
Mark.

**Comment by Marcool04** [comment] 2023-12-16 10:39
The following workaround allows building:

```bash
fingerprint="$(gpg --homedir=/etc/pacman.d/gnupg/ \
                   --fingerprint \
                   --with-colons \
                   'builder@archlinuxarm.org' |\
               awk -F: '/^pub:/ {getline; print $10}')"
gpg --homedir=/etc/pacman.d/gnupg/ --quick-sign-key "$fingerprint"
```

obviously, it doesn't solve anything...

**Comment by fwcd** [comment] 2023-12-16 12:06
Should be fixed with 6a6594e2afab12aece12ac64c32e828fe7139743. I have no idea why this happened, I would have expected upstream ALARM to have these issues too if they indeed use a deprecated algorithm, yet I could not find anything on the forums. Fortunately, this relatively obscure GPG flag lets us import the ALARM key without disabling signature checking entirely (e.g. by setting `SigLevel = TrustAll` or `SigLevel = None` in `/etc/pacman.conf`).

**Closed as completed by fwcd** 2023-12-16 12:06 UTC

**Comment by Marcool04** [comment] 2023-12-16 14:19
Verified to be working! Thanks a lot @fwcd for helping out here. I agree, seems really strange that this would be a problem in the context of the Github runner but nowhere else 🤔

I did ask on #archlinuxarm on libera.chat the other day, but nobody seemed to have any clue either as to what was going on... Just basically suggested that the issue was on "my side" since obviously for everybody else the keys and trustdb are all fine 🤷‍♂️

Anyhow, kudos for finding a tidy way to get it working.

Regards,
Mark

**Comment by fwcd** [comment] 2023-12-16 15:12
Well, it happened in locally built Docker images too, but it still feels strange given that each image is bootstrapped from scratch using the most recent packages. I couldn't reproduce it in my Arch VM either, but given that I already set it up a while ago, it could have already trusted the relevant keys (i.e. a fresh install might still have the issue).

> Just basically suggested that the issue was on "my side" since obviously for everybody else the keys and trustdb are all fine 🤷‍♂️

I agree that it's hard to get help on these kinds of issues. Partially that is probably just a consequence of being able to run Arch in so vastly different configurations, but the "works on my machine" mentality is obviously not helpful either.

The solution was essentially a lucky coincidence of finding out about this flag in one of the `pacman-key` logs and the fact that `pacman-key` itself is just a shell script. I wouldn't call it "clean", since we're still patching the script, but it's probably as good as it will get for now.

Glad it works for you too again!

**Comment by Marcool04** [comment] 2023-12-16 15:15
oh right yes I hadn't seen you were patching a piece of pacman... indeed, not the most elegant but until we have a better idea what's going on it is, as you said, better than a `SigLevel = None`
